# Generated by Django 3.0.3 on 2020-12-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstanimL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='first_title',
            field=models.CharField(max_length=255, null='CATTLE HEALTH'),
            preserve_default='CATTLE HEALTH',
        ),
        migrations.AddField(
            model_name='front',
            name='second_title',
            field=models.CharField(max_length=255, null='CATTLE EXAMINATIONS'),
            preserve_default='CATTLE EXAMINATIONS',
        ),
    ]
