# Generated by Django 3.0.3 on 2020-12-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstanimL', '0002_auto_20201230_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front',
            name='first_title',
            field=models.CharField(default='CATTLE HEALTH', max_length=255),
        ),
        migrations.AlterField(
            model_name='front',
            name='second_title',
            field=models.CharField(default='CATTLE EXAMINATIONS', max_length=255),
        ),
    ]
