# Generated by Django 3.0.3 on 2020-12-31 06:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstanimL', '0003_auto_20201230_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='banner_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='banner_sw',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='first_box_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='first_box_sw',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='first_title_en',
            field=models.CharField(default='CATTLE HEALTH', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='first_title_sw',
            field=models.CharField(default='CATTLE HEALTH', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='second_box_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='second_box_sw',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='second_title_en',
            field=models.CharField(default='CATTLE EXAMINATIONS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='front',
            name='second_title_sw',
            field=models.CharField(default='CATTLE EXAMINATIONS', max_length=255, null=True),
        ),
    ]
