# Generated by Django 3.0.3 on 2021-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstanimL', '0005_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='sudden',
            field=models.BooleanField(),
        ),
    ]
