# Generated by Django 3.0.3 on 2021-01-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstanimL', '0008_auto_20210102_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='sudden',
            field=models.BooleanField(),
        ),
    ]
