# Generated by Django 3.0.3 on 2021-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstanimL', '0009_auto_20210103_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='sudden',
            field=models.IntegerField(),
        ),
    ]
