# Generated by Django 3.0.3 on 2021-01-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstanimL', '0010_auto_20210103_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='conv',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='diff_breathing',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='sudden',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='unclot_blood',
        ),
    ]
