# Generated by Django 3.0.3 on 2021-01-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstanimL', '0011_auto_20210113_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='incoordination',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='diff_breathing',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
