# Generated by Django 3.0.3 on 2021-02-07 14:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstanimL', '0012_auto_20210113_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animl_id', models.TextField()),
                ('observe_date', models.DateField()),
                ('examine_back', ckeditor.fields.RichTextField()),
                ('examine_front', ckeditor.fields.RichTextField()),
                ('examine_rest', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
