# Generated by Django 3.0.3 on 2020-12-30 06:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
